# Copyright (c) 2023 LogCraft, SAS.
# SPDX-License-Identifier: MPL-2.0

inlineHeader = """
Copyright (c) ${inceptionYear} ${copyrightOwner}.
SPDX-License-Identifier: MPL-2.0
"""

# On enabled, check the license header matches exactly with whitespace.
# Otherwise, strip the header in one line and check.
# default: true
strictCheck = true

excludes = [
    ".github/workflows/**",
    "Cargo.*",

    # Samples folder
    "samples/python/myplugin/client",
    "pyproject.toml",
]

[git]
attrs = 'auto'
ignore = 'auto'

[properties]
inceptionYear = 2023
copyrightOwner = "LogCraft, SAS"