// Copyright (c) 2023 LogCraft, SAS.
// SPDX-License-Identifier: MPL-2.0

package logcraft:splunk;

/// LogCraft - Splunk plugin
world splunk {
    /// Imports
    
    /// Exports
    export logcraft:host/plugin;
  }